/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
char ultr=0, phar=0, gps=0;
#include "stdio.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0        (GUI_ID_USER + 0x00)
#define ID_TEXT_0        (GUI_ID_USER + 0x01)
#define ID_TEXT_1        (GUI_ID_USER + 0x02)
#define ID_TEXT_2        (GUI_ID_USER + 0x03)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ultrason", ID_TEXT_0, 40, 20, 250, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "phares", ID_TEXT_1, 40, 60, 250, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "gps", ID_TEXT_2, 40, 100, 250, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
	char text_ultrason[20];
	char text_phares[20];
	char text_gps[20];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'ultrason'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "Ultrason = 0");
    //
    // Initialization of 'phares'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "Phares = 0");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'gps'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "GPS = 0");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
	case WM_USER: // mise a jour si informations arrivee au niveau thread UART
			
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);		// texte reg
		TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
		sprintf(text_ultrason,"Ultrason = 0x%X",ultr);
		TEXT_SetText(hItem, text_ultrason);
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);		// texte reg
		TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
		sprintf(text_phares,"Phares = 0x%X",phar);
		TEXT_SetText(hItem, text_phares);
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);		// texte reg
		TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
		sprintf(text_gps,"GPS = 0x%X",gps);
		TEXT_SetText(hItem, text_gps);
		break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
